name: restartbox
description: A personal Flutter desktop app for organizing projects and self reset.
publish_to: 'none' # This is a private project and will not be published.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
 sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  country_picker: ^2.0.20
  http: ^0.13.5
  flutter_svg: ^2.0.9
  intl_phone_field: ^3.2.0 
  url_launcher: ^6.1.11
  provider: ^6.0.5
  image_picker: ^0.8.7
  http_parser: ^4.0.0
  path_provider: ^2.1.2
  fluttertoast: ^8.2.1
  flutter_pdfview: ^1.3.2
  media_store_plus: ^0.0.1+1
  dio: ^5.3.3
  share_plus: ^7.2.1
  fl_chart: ^0.65.0
  open_filex: ^4.3.2


  


  cupertino_icons: ^1.0.6
  hijri: ^3.0.0
  mime: ^1.0.6
  foundation: ^0.0.5
  

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  
  flutter_lints: ^3.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/ic_launcher.png"
flutter:
  assets:
    - assets/
    - assets/json/cunterie.json
    - assets/json/countries.json
    - assets/json/ 
    - assets/font/
    - assets/img/

  fonts:
    - family: Effra
      fonts:
        - asset: assets/font/effra_regular.ttf
          weight: 400
        - asset: assets/font/effra_medium.ttf
          weight: 500
        - asset: assets/font/effra_bold.ttf
          weight: 700
    - family: Neosans
      fonts:
        - asset: assets/font/neosans_arabic.ttf
          weight: 400
    - family: Semi
      fonts:
        - asset: assets/font/effra_semi_bold.ttf
          weight: 400

flutter:
  uses-material-design: true
  # To use custom fonts, uncomment the following and include font assets.
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: fonts/Cairo-Regular.ttf
